spring:
  application:
    name: booking-service
  config:
    import: optional:configserver:http://localhost:8888

  kafka:
    bootstrap-servers: localhost:9092
    template:
      default-topic: booking
    consumer:
      group-id: order-service
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            type-mapping: bookingEvent:com.example.leetjourney.bookingservice.event.BookingEvent