spring:
  application:
    name: gateway
  config:
    import: configserver:http://localhost:8888
management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway

  endpoint:
    gateway:
      access: unrestricted